package ai.emtizzle.pontoufleintercom;
import android.Manifest; import android.app.Activity; import android.content.ActivityNotFoundException; import android.content.Intent; import android.content.pm.PackageManager; import android.net.Uri; import android.os.Bundle; import android.speech.RecognizerIntent; import android.widget.TextView; import java.util.ArrayList; import java.util.Locale;
public class MainActivity extends Activity {
private static final int SPEECH=41,MIC=42; private TextView status,transcript;
@Override public void onCreate(Bundle s){super.onCreate(s);setContentView(R.layout.activity_main);status=findViewById(R.id.status);transcript=findViewById(R.id.transcript);findViewById(R.id.talk).setOnClickListener(v->listen());findViewById(R.id.openMuse).setOnClickListener(v->openMuse());if(getIntent().getBooleanExtra("listen_now",false))listen();}
private void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;} Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,Locale.getDefault());i.putExtra(RecognizerIntent.EXTRA_PROMPT,"Tell Pontoufle what you need…");status.setText("PONTOUFLE IS LISTENING…");try{startActivityForResult(i,SPEECH);}catch(ActivityNotFoundException e){status.setText("THE FLUFF CANNOT HEAR YOU 💀");transcript.setText("No speech recognition service is available.");}}
@Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==MIC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)listen();else if(r==MIC)status.setText("MICROPHONE DENIED — FLOOF RESPECTS BOUNDARIES");}
@Override protected void onActivityResult(int r,int result,Intent d){super.onActivityResult(r,result,d);if(r==SPEECH&&result==RESULT_OK&&d!=null){ArrayList<String>w=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(w!=null&&!w.isEmpty()){transcript.setText(w.get(0));status.setText("REQUEST CAPTURED ✨");}}}
private void openMuse(){Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("https://applink.muse.ai"));try{startActivity(i);}catch(ActivityNotFoundException e){status.setText("THE FLUFF HAS LOST CONTACT WITH COMMAND");}}
}